services:
  fastapi:
    build:
      context: ../../
      dockerfile: infrastructure/images/applications/FastAPI/Dockerfile

    container_name: fastapi

    env_file:
      - ../../applications/FastAPI/.env

  nginx:
    build:
      context: ../../
      dockerfile: infrastructure/images/gateway/nginx/Dockerfile

    container_name: nginx

    ports:
      - "8080:80"

    depends_on:
      - fastapi